### ISSUE TITLE
Could you released the pre-trained model weights?

### ISSUE THREAD

**Issue by LTEnjoy** [wukevin/proteinclip#1]
Hello, nice to see the great work!

I'm interested in your pre-trained models and I wonder do you plan to release your pre-trained models for public use?

**Comment by wukevin** [comment]
Pre-trained model weights are available under the "pretrained" directory (https://github.com/wukevin/proteinclip/tree/main/pretrained). I have also updated the README with a guide on how to use provided functions to load these models and run inference: https://github.com/wukevin/proteinclip/commit/3b5ffb2f6921e0b811e278b5aec7ed0448aeed40.

Thanks for bringing this up!
